CONF_MYSQL_BUFFERED = "buffered"
CONF_MYSQL_HOST = "host"
CONF_MYSQL_PORT = "port"
CONF_MYSQL_USERNAME = "username"
CONF_MYSQL_PASSWORD = "password"
CONF_MYSQL_DB = "db"
CONF_MYSQL_TIMEOUT = "timeout"

# Defaults
DEFAULT_MYSQL_BUFFERED = True
DEFAULT_MYSQL_PORT = 3306
DEFAULT_MYSQL_TIMEOUT = 10
